development:
  user: 
  password: 
  url: http://127.0.0.1:8080/fedora/rest
  base_path: /dev
test:
  user: 
  password: 
  url: http://127.0.0.1:8080/fedora/rest
  base_path: /test
production:
  user: 
  password: 
  url: http://127.0.0.1:8080/fedora/rest
  base_path: /prod
