# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c762bdd76803530c842d55ed130bc03162e9dbf3b98aa8c39bc00741dee178e6264f90b5699b7b76eff1803f4bed2a6236d7037a0092f890f9bf54101575f9

test:
  secret_key_base: e0f2fe94b0e8441c582226f2759c06a0a667897bd220a835bd22104909dde9178f76ff06ab6e6d0e0353b002ec74093cf900d18f5805935a12ee1f62c5b082d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
